apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramiz-deployment
  namespace: ramiz
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ramiz-nginx
  template:
    metadata:
      labels:
        app: ramiz-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80